"""Self-contained HTML report for a run record (figures embedded as PNG data URIs).

The report is rendered from the same dictionary that is written to ``record.json``, so the
two can never disagree. All text taken from input files is HTML-escaped.
"""
from __future__ import annotations

import base64
import json
from collections.abc import Mapping
from html import escape
from typing import Any

_STATUS_CLASS = {"PASS": "pass", "FAIL": "fail"}
_CSS = """
:root{color-scheme:light dark;--fg:#1f2328;--muted:#59636e;--bg:#fff;--card:#f6f8fa;--line:#d1d9e0;
--pass:#1a7f37;--fail:#cf222e;--warn:#9a6700;--na:#59636e}
@media (prefers-color-scheme:dark){:root{--fg:#e6edf3;--muted:#9198a1;--bg:#0d1117;--card:#151b23;
--line:#3d444d;--pass:#3fb950;--fail:#f85149;--warn:#d29922;--na:#9198a1}}
body{font:15px/1.5 system-ui,-apple-system,"Segoe UI",Roboto,sans-serif;color:var(--fg);background:var(--bg);
max-width:1000px;margin:32px auto;padding:0 16px}
h1{margin:0 0 4px;font-size:1.6rem}h2{margin:28px 0 8px;font-size:1.15rem;border-bottom:1px solid var(--line)}
.sub{color:var(--muted);margin:0 0 16px}
.badge{display:inline-block;padding:4px 12px;border-radius:6px;font-weight:700;color:#fff;background:var(--na)}
.badge.pass{background:var(--pass)}.badge.fail{background:var(--fail)}
.banner{border:2px solid var(--warn);border-radius:8px;padding:10px 14px;margin:16px 0;font-weight:600}
.note{background:var(--card);border-radius:8px;padding:10px 14px;margin:16px 0}
table{border-collapse:collapse;width:100%;font-size:14px}th,td{border:1px solid var(--line);padding:6px 8px;
text-align:left;vertical-align:top}th{background:var(--card)}td.num{font-variant-numeric:tabular-nums;white-space:nowrap}
.pass{color:var(--pass);font-weight:700}.fail{color:var(--fail);font-weight:700}
pre{background:var(--card);padding:10px;border-radius:6px;overflow-x:auto;font-size:13px}
img{max-width:100%;height:auto;background:#fff;border:1px solid var(--line);border-radius:6px}
ul.warn li{color:var(--warn)}footer{margin:32px 0;color:var(--muted);font-size:13px}
code{font-size:13px}
"""


def render_run_report(record: Mapping[str, Any], figures: Mapping[str, bytes] | None = None) -> str:
    analysis = record.get("analysis", {})
    source = record.get("source", {})
    validation = record.get("validation", {})
    software = record.get("software", {})
    overall = str(validation.get("overall", "NOT_EVALUATED"))
    title = str(analysis.get("title") or "OpenECE Lab run")

    parts = [
        "<!doctype html>",
        '<html lang="en"><head><meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        f"<title>{escape(title)}</title><style>{_CSS}</style></head><body>",
        f"<h1>{escape(title)}</h1>",
        f'<p class="sub">{escape(str(analysis.get("type", "")))} analysis &middot; run '
        f'<code>{escape(str(record.get("run_id", "")))}</code> &middot; {escape(str(record.get("created_utc", "")))}</p>',
        f'<p><span class="badge {_STATUS_CLASS.get(overall, "")}">{escape(_overall_label(overall))}</span></p>',
        _origin_banner(source),
        "<h2>Results</h2>",
        _results_table(record.get("results", {})),
        "<h2>Validation</h2>",
        _validation_section(validation),
    ]
    if figures:
        parts.append("<h2>Figures</h2>")
        for name, png in figures.items():
            data = base64.b64encode(png).decode("ascii")
            parts.append(f'<p><img alt="{escape(name)}" src="data:image/png;base64,{data}"></p>')
    warnings = record.get("warnings") or []
    if warnings:
        parts.append("<h2>Warnings</h2><ul class=\"warn\">")
        parts.extend(f"<li>{escape(str(w))}</li>" for w in warnings)
        parts.append("</ul>")
    parts += [
        "<h2>Source</h2>", _source_section(source),
        "<h2>Parameters</h2>", _pre(analysis.get("parameters", {})),
        "<h2>Artifacts</h2>", _artifacts_table(record.get("artifacts", [])),
        "<h2>Software</h2>", _pre(software),
    ]
    if record.get("invocation"):
        parts += ["<h2>Invocation</h2>", _pre(record["invocation"])]
    parts.append(
        f"<footer>Generated by OpenECE Lab {escape(str(software.get('version', '')))}. "
        "The machine-readable record of this run is <code>record.json</code> in the same folder.</footer>"
    )
    parts.append("</body></html>")
    return "\n".join(p for p in parts if p) + "\n"


def _overall_label(overall: str) -> str:
    return {"PASS": "PASS", "FAIL": "FAIL"}.get(overall, "NOT EVALUATED (no requirements)")


def _origin_banner(source: Mapping[str, Any]) -> str:
    if source.get("simulated") is True:
        return ('<div class="banner">SIMULATED DATA: produced by a mock instrument backend. '
                "This is not a physical measurement.</div>")
    if source.get("kind") == "file":
        return ('<div class="note">Data imported from a file. OpenECE Lab records its origin and checksum '
                "but cannot verify whether it is a physical measurement; see the file comments below.</div>")
    if source.get("simulated") is None:
        return '<div class="banner">Data origin unknown: the instrument backend did not declare whether it is simulated.</div>'
    return ""


def _results_table(results: Mapping[str, Any]) -> str:
    rows = ["<table><tr><th>Result</th><th>Value</th><th>Unit</th><th>Description</th></tr>"]
    for name, item in results.items():
        note = f" ({item['note']})" if item.get("note") else ""
        rows.append(
            f"<tr><td><code>{escape(name)}</code></td><td class=\"num\">{_fmt(item.get('value'))}</td>"
            f"<td>{escape(_unit(item.get('unit')))}</td><td>{escape(str(item.get('description', '')))}{escape(note)}</td></tr>"
        )
    rows.append("</table>")
    return "".join(rows)


def _validation_section(validation: Mapping[str, Any]) -> str:
    checks = validation.get("checks") or []
    spec = validation.get("spec")
    head = ""
    if spec:
        head = f"<p>Specification: <strong>{escape(str(spec.get('name', '')))}</strong>"
        if spec.get("path"):
            head += f" (<code>{escape(str(spec['path']))}</code>)"
        head += "</p>"
    if not checks:
        return head + "<p>No requirements were given, so this run is not evaluated as PASS or FAIL.</p>"
    rows = ["<table><tr><th>Requirement</th><th>Value</th><th>Min</th><th>Max</th><th>Unit</th><th>Status</th><th>Detail</th></tr>"]
    for c in checks:
        status = str(c.get("status"))
        rows.append(
            f"<tr><td><code>{escape(str(c.get('name')))}</code></td><td class=\"num\">{_fmt(c.get('value'))}</td>"
            f"<td class=\"num\">{_fmt(c.get('min'), blank=True)}</td><td class=\"num\">{_fmt(c.get('max'), blank=True)}</td>"
            f"<td>{escape(_unit(c.get('unit')))}</td><td class=\"{_STATUS_CLASS.get(status, '')}\">{escape(status)}</td>"
            f"<td>{escape(str(c.get('detail', '')))}</td></tr>"
        )
    rows.append("</table>")
    return head + "".join(rows)


def _source_section(source: Mapping[str, Any]) -> str:
    if source.get("kind") == "file":
        rows = [
            ("File", source.get("path")), ("Absolute path", source.get("absolute_path")),
            ("Format", source.get("format")), ("Size", f"{source.get('size_bytes')} bytes"),
            ("SHA-256", source.get("sha256")),
        ]
        table = "<table>" + "".join(
            f"<tr><th>{escape(k)}</th><td><code>{escape(str(v))}</code></td></tr>" for k, v in rows
        ) + "</table>"
        comments = (source.get("metadata") or {}).get("comments") or []
        if comments:
            table += "<p>File comments:</p><pre>" + escape("\n".join(str(c) for c in comments)) + "</pre>"
        details = {k: v for k, v in (source.get("metadata") or {}).items() if k != "comments"}
        return table + "<p>Import details:</p>" + _pre(details)
    return _pre(source)


def _artifacts_table(artifacts) -> str:
    rows = ["<table><tr><th>File</th><th>Kind</th><th>Description</th></tr>"]
    for a in artifacts:
        rows.append(
            f"<tr><td><code>{escape(str(a.get('path')))}</code></td><td>{escape(str(a.get('kind')))}</td>"
            f"<td>{escape(str(a.get('description', '')))}</td></tr>"
        )
    rows.append("</table>")
    return "".join(rows)


def _pre(value: Any) -> str:
    return "<pre>" + escape(json.dumps(value, indent=2, ensure_ascii=False)) + "</pre>"


def _fmt(value: Any, blank: bool = False) -> str:
    if value is None:
        return "" if blank else "n/a"
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, float):
        return escape(f"{value:.6g}")
    return escape(str(value))


def _unit(unit: Any) -> str:
    return "not specified" if unit is None else str(unit)
