"""Regenerate the synthetic example datasets in ``examples/``.

All files are SYNTHETIC: they come from the documented models below plus seeded noise, so they
are reproducible and have a known ground truth for the tests. They are not physical
measurements, and each file says so. Do not edit the generated files by hand; change this
script and regenerate:

    python scripts/generate_examples.py --force
"""
from __future__ import annotations

import argparse
import io
import math
import struct
import sys
from pathlib import Path

import numpy as np
from scipy.io import wavfile

SEED = 2026

# RC low-pass frequency sweep
RC_R_OHM = 10e3
RC_C_F = 10e-9
RC_POINTS = 61  # 100 Hz .. 100 kHz, 20 points per decade
RC_MAGNITUDE_NOISE_DB = 0.02
RC_PHASE_NOISE_DEG = 0.2

# DC motor speed loop step response (second-order closed loop)
MOTOR_WN_RAD_S = 25.0
MOTOR_ZETA = 0.6
MOTOR_DC_GAIN = 0.985  # proportional loop: 1.5 % steady-state error
MOTOR_SETPOINT_RPM = 1000.0
MOTOR_SAMPLE_RATE_HZ = 1000.0
MOTOR_PRETRIGGER_S = 0.05
MOTOR_RECORD_S = 0.95
MOTOR_NOISE_RPM = 2.0

# Sound-card style capture of a 1 kHz test tone
SIGNAL_SAMPLE_RATE_HZ = 48_000
SIGNAL_DURATION_S = 0.5
SIGNAL_DC_FS = 0.01
SIGNAL_TONES = ((1000.0, 0.5), (2000.0, 0.005), (3000.0, 0.0016), (50.0, 0.003))  # (Hz, peak amplitude in FS)
SIGNAL_NOISE_FS = 0.0005


def rc_cutoff_hz() -> float:
    return 1.0 / (2.0 * math.pi * RC_R_OHM * RC_C_F)


def rc_frequencies_hz() -> np.ndarray:
    return np.geomspace(100.0, 100e3, RC_POINTS)


def rc_model(frequency_hz: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Noise-free magnitude (dB) and phase (deg) of the RC low-pass."""
    h = 1.0 / (1.0 + 1j * frequency_hz / rc_cutoff_hz())
    return 20.0 * np.log10(np.abs(h)), np.degrees(np.angle(h))


def rc_sweep_csv() -> str:
    rng = np.random.default_rng(SEED)
    f = rc_frequencies_hz()
    magnitude, phase = rc_model(f)
    magnitude = magnitude + rng.normal(0.0, RC_MAGNITUDE_NOISE_DB, f.size)
    phase = phase + rng.normal(0.0, RC_PHASE_NOISE_DEG, f.size)
    lines = [
        "# OpenECE Lab example: RC low-pass frequency sweep",
        "# SYNTHETIC DATA generated by scripts/generate_examples.py - not a physical measurement.",
        f"# Model: first-order RC low-pass, R = 10 kOhm, C = 10 nF, nominal cutoff {rc_cutoff_hz():.2f} Hz",
        f"# Added noise: magnitude sigma {RC_MAGNITUDE_NOISE_DB} dB, phase sigma {RC_PHASE_NOISE_DEG} deg (seed {SEED})",
        "Frequency (Hz),Magnitude (dB),Phase (deg)",
    ]
    lines += [f"{fi:.6g},{mi:.4f},{pi:.3f}" for fi, mi, pi in zip(f, magnitude, phase)]
    return "\n".join(lines) + "\n"


def motor_time_s() -> np.ndarray:
    before = round(MOTOR_PRETRIGGER_S * MOTOR_SAMPLE_RATE_HZ)
    after = round(MOTOR_RECORD_S * MOTOR_SAMPLE_RATE_HZ)
    return np.arange(-before, after + 1) / MOTOR_SAMPLE_RATE_HZ


def motor_model_rpm(t: np.ndarray) -> np.ndarray:
    """Noise-free underdamped second-order step response; the step is applied at t = 0."""
    damped = MOTOR_WN_RAD_S * math.sqrt(1.0 - MOTOR_ZETA**2)
    tp = np.maximum(t, 0.0)
    envelope = np.exp(-MOTOR_ZETA * MOTOR_WN_RAD_S * tp) / math.sqrt(1.0 - MOTOR_ZETA**2)
    unit_step = 1.0 - envelope * np.sin(damped * tp + math.acos(MOTOR_ZETA))
    return np.where(t >= 0, MOTOR_SETPOINT_RPM * MOTOR_DC_GAIN * unit_step, 0.0)


def motor_step_csv() -> str:
    rng = np.random.default_rng(SEED + 1)
    t = motor_time_s()
    speed = motor_model_rpm(t) + rng.normal(0.0, MOTOR_NOISE_RPM, t.size)
    lines = [
        "# OpenECE Lab example: DC motor speed-loop step response",
        "# SYNTHETIC DATA generated by scripts/generate_examples.py - not a physical measurement.",
        f"# Model: second-order closed loop, wn = {MOTOR_WN_RAD_S:g} rad/s, zeta = {MOTOR_ZETA:g}, "
        f"DC gain {MOTOR_DC_GAIN:g} (1.5 % steady-state error)",
        f"# Step: speed setpoint 0 -> {MOTOR_SETPOINT_RPM:g} rpm at t = 0 s; logging starts "
        f"{MOTOR_PRETRIGGER_S * 1000:g} ms before the step at {MOTOR_SAMPLE_RATE_HZ:g} Hz",
        f"# Added noise: sigma {MOTOR_NOISE_RPM:g} rpm (seed {SEED + 1})",
        "time (s),speed (rpm)",
    ]
    lines += [f"{ti:.3f},{yi:.2f}" for ti, yi in zip(t, speed)]
    return "\n".join(lines) + "\n"


def signal_time_s() -> np.ndarray:
    return np.arange(round(SIGNAL_SAMPLE_RATE_HZ * SIGNAL_DURATION_S)) / SIGNAL_SAMPLE_RATE_HZ


def signal_model_fs(t: np.ndarray) -> np.ndarray:
    """Noise-free test signal in units of digital full scale."""
    x = np.full_like(t, SIGNAL_DC_FS)
    for frequency, amplitude in SIGNAL_TONES:
        x += amplitude * np.sin(2.0 * math.pi * frequency * t)
    return x


def signal_wav_bytes() -> bytes:
    rng = np.random.default_rng(SEED + 2)
    t = signal_time_s()
    x = signal_model_fs(t) + rng.normal(0.0, SIGNAL_NOISE_FS, t.size)
    pcm = np.clip(np.round(x * 32768.0), -32768, 32767).astype("<i2")
    buffer = io.BytesIO()
    wavfile.write(buffer, SIGNAL_SAMPLE_RATE_HZ, pcm)
    tones = ", ".join(f"{f:g} Hz at {a:g} FS" for f, a in SIGNAL_TONES)
    return _with_info_chunk(buffer.getvalue(), {
        "ICMT": "SYNTHETIC DATA generated by scripts/generate_examples.py - not a physical measurement. "
                f"DC {SIGNAL_DC_FS:g} FS; tones {tones}; noise sigma {SIGNAL_NOISE_FS:g} FS (seed {SEED + 2}).",
        "ISFT": "OpenECE Lab scripts/generate_examples.py",
    })


def _with_info_chunk(wav: bytes, info: dict[str, str]) -> bytes:
    """Append a RIFF LIST/INFO chunk (text metadata) and fix up the RIFF size field."""
    body = b"INFO"
    for key, text in info.items():
        data = text.encode("ascii") + b"\x00"
        body += key.encode("ascii") + struct.pack("<I", len(data)) + data + (b"\x00" if len(data) % 2 else b"")
    out = wav + b"LIST" + struct.pack("<I", len(body)) + body
    return out[:4] + struct.pack("<I", len(out) - 8) + out[8:]


def example_files() -> dict[str, bytes]:
    return {
        "rc_sweep.csv": rc_sweep_csv().encode("utf-8"),
        "motor_step.csv": motor_step_csv().encode("utf-8"),
        "signal.wav": signal_wav_bytes(),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate the synthetic example datasets.")
    parser.add_argument("--out-dir", type=Path, default=Path(__file__).resolve().parent.parent / "examples")
    parser.add_argument("--force", action="store_true", help="overwrite existing example files")
    args = parser.parse_args(argv)
    files = example_files()
    existing = [name for name in files if (args.out_dir / name).exists()]
    if existing and not args.force:
        print(f"refusing to overwrite {', '.join(existing)} in {args.out_dir}; pass --force", file=sys.stderr)
        return 1
    args.out_dir.mkdir(parents=True, exist_ok=True)
    for name, data in files.items():
        (args.out_dir / name).write_bytes(data)
        print(f"wrote {args.out_dir / name} ({len(data)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
